package model

import (
	"time"
)

// AlertRule defines a rule for triggering alerts based on log patterns.
type AlertRule struct {
	// ID is the unique identifier for the rule.
	ID string `json:"id"`
	// Name is a human-readable name for the rule.
	Name string `json:"name"`
	// Description provides details about the rule.
	Description string `json:"description,omitempty"`
	// Status is the current status of the rule.
	Status RuleStatus `json:"status"`
	// Condition defines the triggering condition.
	Condition RuleCondition `json:"condition"`
	// Window is the time window for evaluating the condition.
	Window time.Duration `json:"window"`
	// Threshold is the value that triggers the alert.
	Threshold float64 `json:"threshold"`
	// Severity is the severity of alerts generated by this rule.
	Severity Severity `json:"severity"`
	// Cooldown is the minimum time between alerts for this rule.
	Cooldown time.Duration `json:"cooldown"`
	// LastFiredAt is when the rule last triggered an alert.
	LastFiredAt *time.Time `json:"last_fired_at,omitempty"`
	// CreatedAt is when the rule was created.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt is when the rule was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Tags are metadata tags for the rule.
	Tags map[string]string `json:"tags,omitempty"`
}

// RuleCondition defines the condition for a rule.
type RuleCondition struct {
	// Type is the condition type.
	Type RuleConditionType `json:"type"`
	// Level is the log level to filter on (for level/count conditions).
	Level LogLevel `json:"level,omitempty"`
	// Source is the source to filter on.
	Source string `json:"source,omitempty"`
	// Service is the service to filter on.
	Service string `json:"service,omitempty"`
	// Keywords are keywords to match in log messages.
	Keywords []string `json:"keywords,omitempty"`
	// MinCount is the minimum count for count-based conditions.
	MinCount int `json:"min_count,omitempty"`
}

// NewAlertRule creates a new AlertRule with defaults.
func NewAlertRule(name string, condition RuleCondition) *AlertRule {
	now := time.Now()
	return &AlertRule{
		ID:          GenerateID(),
		Name:        name,
		Status:      RuleActive,
		Condition:   condition,
		Window:      5 * time.Minute,
		Threshold:   5,
		Severity:    SeverityMedium,
		Cooldown:    5 * time.Minute,
		CreatedAt:   now,
		UpdatedAt:   now,
		Tags:        make(map[string]string),
	}
}

// IsActive checks if the rule is active.
func (r *AlertRule) IsActive() bool {
	return r.Status == RuleActive
}

// IsPaused checks if the rule is paused.
func (r *AlertRule) IsPaused() bool {
	return r.Status == RulePaused
}

// Activate activates the rule.
func (r *AlertRule) Activate() {
	r.Status = RuleActive
	r.UpdatedAt = time.Now()
}

// Pause pauses the rule.
func (r *AlertRule) Pause() {
	r.Status = RulePaused
	r.UpdatedAt = time.Now()
}

// Archive archives the rule.
func (r *AlertRule) Archive() {
	r.Status = RuleArchived
	r.UpdatedAt = time.Now()
}

// Update updates the rule fields.
func (r *AlertRule) Update(name, description string) {
	if name != "" {
		r.Name = name
	}
	if description != "" {
		r.Description = description
	}
	r.UpdatedAt = time.Now()
}

// CanFire checks if the rule can fire (not in cooldown).
func (r *AlertRule) CanFire(now time.Time) bool {
	if !r.IsActive() {
		return false
	}
	if r.LastFiredAt == nil {
		return true
	}
	return now.After(r.LastFiredAt.Add(r.Cooldown))
}

// MarkFired marks the rule as having fired.
func (r *AlertRule) MarkFired(t time.Time) {
	r.LastFiredAt = &t
	r.UpdatedAt = t
}

// ToMap converts the rule to a map for serialization.
func (r *AlertRule) ToMap() map[string]interface{} {
	result := map[string]interface{}{
		"id":          r.ID,
		"name":        r.Name,
		"description": r.Description,
		"status":      r.Status,
		"condition": map[string]interface{}{
			"type":     r.Condition.Type,
			"level":    r.Condition.Level,
			"source":   r.Condition.Source,
			"service":  r.Condition.Service,
			"keywords": r.Condition.Keywords,
		},
		"window":    r.Window,
		"threshold": r.Threshold,
		"severity":  r.Severity,
		"cooldown":  r.Cooldown,
		"created_at": r.CreatedAt,
		"updated_at": r.UpdatedAt,
		"tags":       r.Tags,
	}
	if r.LastFiredAt != nil {
		result["last_fired_at"] = *r.LastFiredAt
	}
	return result
}

// Validate checks if the rule has valid values.
func (r *AlertRule) Validate() []string {
	var errors []string

	if r.Name == "" {
		errors = append(errors, "rule name is required")
	}
	if r.Window <= 0 {
		errors = append(errors, "window must be positive")
	}
	if r.Threshold <= 0 {
		errors = append(errors, "threshold must be positive")
	}
	if r.Condition.Type == "" {
		errors = append(errors, "condition type is required")
	}

	return errors
}
